import type { Metadata } from 'next/types';
import { Quattrocento, Roboto } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Navbar from '@/components/Navbar';
import Providers from '@/components/Providers';

const font = Quattrocento({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});
const font1 = Roboto({
  weight: ['700'],
  style: ['italic'],
  subsets: ['latin'],
  display: 'swap',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <Providers>
        <body className={cn('min-h-screen antialised grainy', font1.className)}>
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
// childrens are the page of the app and body is the entire app
